// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ClientProto.proto

package pt.groupG.grpc;

public final class ClientProtos {
  private ClientProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_grpc_JoinMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_grpc_JoinMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_grpc_BooleanMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_grpc_BooleanMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_grpc_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_grpc_EmptyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_grpc_NodeDetailsMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_grpc_NodeDetailsMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_grpc_NodeDetailsListMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_grpc_NodeDetailsListMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_grpc_NodeIdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_grpc_NodeIdMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_grpc_NodeIdListMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_grpc_NodeIdListMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/ClientProto.proto\022\016pt.g" +
      "roupG.grpc\",\n\013JoinMessage\022\017\n\007address\030\001 \001" +
      "(\t\022\014\n\004port\030\002 \001(\005\"\037\n\016BooleanMessage\022\r\n\005va" +
      "lue\030\001 \001(\010\"\016\n\014EmptyMessage\"C\n\022NodeDetails" +
      "Message\022\017\n\007address\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\016" +
      "\n\006nodeid\030\003 \001(\t\"K\n\026NodeDetailsListMessage" +
      "\0221\n\005nodes\030\001 \003(\0132\".pt.groupG.grpc.NodeDet" +
      "ailsMessage\"\037\n\rNodeIdMessage\022\016\n\006nodeid\030\001" +
      " \001(\t\"A\n\021NodeIdListMessage\022,\n\005nodes\030\001 \003(\013" +
      "2\035.pt.groupG.grpc.NodeIdMessage2\210\003\n\rClie" +
      "ntService\022B\n\004join\022\033.pt.groupG.grpc.JoinM" +
      "essage\032\035.pt.groupG.grpc.NodeIdMessage\022D\n" +
      "\004ping\022\034.pt.groupG.grpc.EmptyMessage\032\036.pt" +
      ".groupG.grpc.BooleanMessage\022Q\n\010findNode\022" +
      "\035.pt.groupG.grpc.NodeIdMessage\032&.pt.grou" +
      "pG.grpc.NodeDetailsListMessage\022R\n\tfindVa" +
      "lue\022\035.pt.groupG.grpc.NodeIdMessage\032&.pt." +
      "groupG.grpc.NodeDetailsListMessage\022F\n\005st" +
      "ore\022\035.pt.groupG.grpc.NodeIdMessage\032\036.pt." +
      "groupG.grpc.BooleanMessageB\020B\014ClientProt" +
      "osP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pt_groupG_grpc_JoinMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_groupG_grpc_JoinMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_grpc_JoinMessage_descriptor,
        new java.lang.String[] { "Address", "Port", });
    internal_static_pt_groupG_grpc_BooleanMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_groupG_grpc_BooleanMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_grpc_BooleanMessage_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_pt_groupG_grpc_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_groupG_grpc_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_grpc_EmptyMessage_descriptor,
        new java.lang.String[] { });
    internal_static_pt_groupG_grpc_NodeDetailsMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pt_groupG_grpc_NodeDetailsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_grpc_NodeDetailsMessage_descriptor,
        new java.lang.String[] { "Address", "Port", "Nodeid", });
    internal_static_pt_groupG_grpc_NodeDetailsListMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pt_groupG_grpc_NodeDetailsListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_grpc_NodeDetailsListMessage_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_pt_groupG_grpc_NodeIdMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pt_groupG_grpc_NodeIdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_grpc_NodeIdMessage_descriptor,
        new java.lang.String[] { "Nodeid", });
    internal_static_pt_groupG_grpc_NodeIdListMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pt_groupG_grpc_NodeIdListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_grpc_NodeIdListMessage_descriptor,
        new java.lang.String[] { "Nodes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
