// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ClientProto.proto

package pt.groupG.grpc;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.groupG.grpc.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
