// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ClientProto.proto

package pt.groupG.communication;

public interface BooleanMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.groupG.communication.BooleanMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool value = 1;</code>
   */
  boolean getValue();
}
