// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ClientProto.proto

package pt.groupG.communication;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_JoinMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_JoinMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_BooleanMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_BooleanMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_EmptyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/ClientProto.proto\022\027pt.g" +
      "roupG.communication\",\n\013JoinMessage\022\017\n\007ad" +
      "dress\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\"\037\n\016BooleanMess" +
      "age\022\r\n\005value\030\001 \001(\010\"\016\n\014EmptyMessage2\265\001\n\006C" +
      "lient\022S\n\004join\022%.pt.groupG.communication." +
      "EmptyMessage\032$.pt.groupG.communication.J" +
      "oinMessage\022V\n\004ping\022%.pt.groupG.communica" +
      "tion.EmptyMessage\032\'.pt.groupG.communicat" +
      "ion.BooleanMessageB\017B\013ClientProtoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pt_groupG_communication_JoinMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_groupG_communication_JoinMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_JoinMessage_descriptor,
        new java.lang.String[] { "Address", "Port", });
    internal_static_pt_groupG_communication_BooleanMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_groupG_communication_BooleanMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_BooleanMessage_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_pt_groupG_communication_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_groupG_communication_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_EmptyMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
