// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ClientProto.proto

package pt.groupG.communication;

public interface JoinMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.groupG.communication.JoinMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
