// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ServerProto.proto

package pt.groupG.communication;

public interface NodeIdMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.groupG.communication.NodeIdMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeid = 1;</code>
   */
  java.lang.String getNodeid();
  /**
   * <code>string nodeid = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeidBytes();
}
