// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ServerProto.proto

package pt.groupG.communication;

public interface NodeDetailsListMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.groupG.communication.NodeDetailsListMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pt.groupG.communication.NodeDetailsMessage nodes = 1;</code>
   */
  java.util.List<pt.groupG.communication.NodeDetailsMessage> 
      getNodesList();
  /**
   * <code>repeated .pt.groupG.communication.NodeDetailsMessage nodes = 1;</code>
   */
  pt.groupG.communication.NodeDetailsMessage getNodes(int index);
  /**
   * <code>repeated .pt.groupG.communication.NodeDetailsMessage nodes = 1;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .pt.groupG.communication.NodeDetailsMessage nodes = 1;</code>
   */
  java.util.List<? extends pt.groupG.communication.NodeDetailsMessageOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .pt.groupG.communication.NodeDetailsMessage nodes = 1;</code>
   */
  pt.groupG.communication.NodeDetailsMessageOrBuilder getNodesOrBuilder(
      int index);
}
