// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ServerProto.proto

package pt.groupG.communication;

public interface NodeDetailsMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.groupG.communication.NodeDetailsMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>string nodeid = 3;</code>
   */
  java.lang.String getNodeid();
  /**
   * <code>string nodeid = 3;</code>
   */
  com.google.protobuf.ByteString
      getNodeidBytes();
}
