// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ServerProto.proto

package pt.groupG.communication;

public interface NodeIdListMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.groupG.communication.NodeIdListMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pt.groupG.communication.NodeIdMessage nodes = 1;</code>
   */
  java.util.List<pt.groupG.communication.NodeIdMessage> 
      getNodesList();
  /**
   * <code>repeated .pt.groupG.communication.NodeIdMessage nodes = 1;</code>
   */
  pt.groupG.communication.NodeIdMessage getNodes(int index);
  /**
   * <code>repeated .pt.groupG.communication.NodeIdMessage nodes = 1;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .pt.groupG.communication.NodeIdMessage nodes = 1;</code>
   */
  java.util.List<? extends pt.groupG.communication.NodeIdMessageOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .pt.groupG.communication.NodeIdMessage nodes = 1;</code>
   */
  pt.groupG.communication.NodeIdMessageOrBuilder getNodesOrBuilder(
      int index);
}
