// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ServerProto.proto

package pt.groupG.communication;

public final class ServerProto {
  private ServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_JoinMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_JoinMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_BooleanMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_BooleanMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_EmptyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_NodeDetailsMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_NodeDetailsMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_NodeDetailsListMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_NodeDetailsListMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_NodeIdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_NodeIdMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_groupG_communication_NodeIdListMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_groupG_communication_NodeIdListMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/ServerProto.proto\022\027pt.g" +
      "roupG.communication\",\n\013JoinMessage\022\017\n\007ad" +
      "dress\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\"\037\n\016BooleanMess" +
      "age\022\r\n\005value\030\001 \001(\010\"\016\n\014EmptyMessage\"C\n\022No" +
      "deDetailsMessage\022\017\n\007address\030\001 \001(\t\022\014\n\004por" +
      "t\030\002 \001(\005\022\016\n\006nodeid\030\003 \001(\t\"T\n\026NodeDetailsLi" +
      "stMessage\022:\n\005nodes\030\001 \003(\0132+.pt.groupG.com" +
      "munication.NodeDetailsMessage\"\037\n\rNodeIdM" +
      "essage\022\016\n\006nodeid\030\001 \001(\t\"J\n\021NodeIdListMess" +
      "age\0225\n\005nodes\030\001 \003(\0132&.pt.groupG.communica" +
      "tion.NodeIdMessage2\200\003\n\006Server\022S\n\004join\022%." +
      "pt.groupG.communication.EmptyMessage\032$.p" +
      "t.groupG.communication.JoinMessage\022V\n\004pi" +
      "ng\022%.pt.groupG.communication.EmptyMessag" +
      "e\032\'.pt.groupG.communication.BooleanMessa" +
      "ge\022c\n\010findNode\022&.pt.groupG.communication" +
      ".NodeIdMessage\032/.pt.groupG.communication" +
      ".NodeDetailsListMessage\022d\n\tfindValue\022&.p" +
      "t.groupG.communication.NodeIdMessage\032/.p" +
      "t.groupG.communication.NodeDetailsListMe" +
      "ssageB\017B\013ServerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pt_groupG_communication_JoinMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_groupG_communication_JoinMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_JoinMessage_descriptor,
        new java.lang.String[] { "Address", "Port", });
    internal_static_pt_groupG_communication_BooleanMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_groupG_communication_BooleanMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_BooleanMessage_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_pt_groupG_communication_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_groupG_communication_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_EmptyMessage_descriptor,
        new java.lang.String[] { });
    internal_static_pt_groupG_communication_NodeDetailsMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pt_groupG_communication_NodeDetailsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_NodeDetailsMessage_descriptor,
        new java.lang.String[] { "Address", "Port", "Nodeid", });
    internal_static_pt_groupG_communication_NodeDetailsListMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pt_groupG_communication_NodeDetailsListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_NodeDetailsListMessage_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_pt_groupG_communication_NodeIdMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pt_groupG_communication_NodeIdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_NodeIdMessage_descriptor,
        new java.lang.String[] { "Nodeid", });
    internal_static_pt_groupG_communication_NodeIdListMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pt_groupG_communication_NodeIdListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_groupG_communication_NodeIdListMessage_descriptor,
        new java.lang.String[] { "Nodes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
